name: Link Issue to PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  link-issue-in-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Issue Number from Branch Name
        id: extract
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oE '[0-9]+$')
          echo "::set-output name=issue_number::$ISSUE_NUMBER"

      - name: Link Issue in PR Description
        if: steps.extract.outputs.issue_number != ''
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = ${{ steps.extract.outputs.issue_number }};
            const prNumber = ${{ github.event.pull_request.number }};
            const repository = ${{ github.repository }};
            const issueLink = `https://github.com/${repository}/issues/${issueNumber}`;
            let originalBody = ${{ github.event.pull_request.body }};
            let body = originalBody.includes(issueLink) ? originalBody : originalBody + `\n\nLinked Issue: [#${issueNumber}](${issueLink})`;

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: body
            });
