name: Preview
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  nx-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 18
          pnpm-version: 8.7.5
      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      - run: git branch --track main origin/main

      - name: nx affected
        run: npx nx format:check
          npx nx affected -t lint,test,build --parallel=3

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: nx-affected
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Deploy to Vercel
  #       run: npx vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod
  #       env:
  #         VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  #         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
